baseURL = "http://paulj.tk/"
languageCode = "en-za"
title = "Paul J"
copyright = "© {year}"
theme = "codex"
disqusShortname = "pauljtk"
googleAnalytics = "UA-40164851-6"

[params]
    author = "Paul Joubert"
    dateFormat = "2006-01-02"

    email = "mailto:hello@paulj.tk"
    twitter = "https://twitter.com/_trespaul"
    instagram = "https://instagram.com/_trespaul"
    github = "https://github.com/trespaul"
    bandcamp = "https://trespaul.bandcamp.com"

    iconOrder = ["Email", "Twitter", "Bandcamp", "GitHub", "Instagram"]

    twitterSite = "@_trespaul"
    twitterAuthor = "@_trespaul"

    showPageTitleInTOC = false


[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
      identifier = "home"
      name = "home"
      title = "home"
      url = "/"
      weight = 1
  
  [[menu.main]]
      identifier = "about"
      name = "about"
      title = "About"
      url = "/about"
      weight = 2
  
  [[menu.main]]
      identifier = "posts"
      name = "posts"
      title = "Posts"
      url = "/posts"
      weight = 3

